apiVersion: v1
kind: Namespace
metadata:
  name: app-example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hello
  namespace: app-example
  labels:
    app: app-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-hello
  template:
    metadata:
      labels:
        app: app-hello
    spec:
      containers:
      - name: app-hello
        image: nginxdemos/nginx-hello:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-example-svc
  namespace: app-example
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http 
  selector:
    app: app-hello

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-example-ingress
  namespace: app-example
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app-example-svc
          servicePort: http